class EnvVarKeys:
    RedisHost = "REDIS_HOST"
    RedisPort = "REDIS_PORT"
    RedisValidationCode = "REDIS_VALIDATION_CODE_DB"
    RedisRegistrationToken = "REDIS_REGISTRATION_TOKEN_DB"
    GenerateFakeCode = "GENERATE_FAKE_CODE"
    GeneratedCodeTimeToLive = "GENERATED_CODE_TIME_TO_LIVE"
    MaximumCodeRequestCount = "MAXIMUM_CODE_REQUEST_COUNT"
    RegistrationTokenTimeToLive = "REGISTRATION_TOKEN_TIME_TO_LIVE"
    RedisAttemptsDB = "REDIS_ATTEMPTS_DB"
